
server:
  port: 9081
spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/side?characterEncoding=utf8&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Seoul'
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'root'
    password: 'root'
  #mariaDB와 동일하게 할것
  flyway:
    enabled: true
    encoding: 'UTF-8'
    locations: 'classpath:/db/migration'
    user: 'root'
    password: 'root'
    url: 'jdbc:mariadb://localhost:3306/side?characterEncoding=utf8&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Seoul'
    baseline-on-migrate: true

    
  #redis 설정
  redis:
    host: localhost
    port: 6379

  #jpa
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      dialect: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MariaDB106Dialect
    database-platform: org.hibernate.dialect.MariaDB106Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 3MB
      #location: C:\sideproject\upload\news\images\     #저장경로
      location: C:/Projects/sideBackend/src/main/upload/news/images/
      max-file-size: 100MB



logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      main.java.com.project.backend.api: debug






